name: Release
on:
  push:
    branches: ["master"]
  workflow_dispatch:
  
jobs:
  release:
    concurrency: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: apt-get update
        run: sudo apt-get update
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21
      - uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.coursier
          key: ${{ runner.os }}-sbt-${{ hashfiles('**/build.sbt') }}
      - run: sbt +test ciReleaseTagNextVersion
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: sbt ++3.4.1 publish
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
